version: "3"

services:
    php_service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        volumes:
            - ./php/app:/var/www/app:cached
            - ./php/logs/:/var/www/log
        environment:
            PHP_IDE_CONFIG: serverName=todo

    nginx_service:
        build:
            context: ./nginx
        volumes:
            - ./nginx/logs/:/var/log/nginx
            - ./php/app:/var/www/app:cached
        ports:
            - 80
        environment:
            APP_HOST: local.todo

    mongodb_service:
        image: mongo:latest
        environment:
            - MONGO_DATA_DIR=/data/db
        volumes:
            - ./mongodb/data/db:/data/db
        ports:
            - 27017:27017
